server.port=${PORT:8087}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example

# Let Hibernate update the schema automatically or create it if it does not exist.
#
# DO NOT DO THIS IN PRODUCTION!
#
# Instead, use Flyway or another controlled way of managing your database schema.
# See https://vaadin.com/docs/latest/building-apps/forms-data/add-flyway for instructions.


spring.datasource.url=jdbc:postgresql://localhost:5432/individual
spring.datasource.username=b7_user
spring.datasource.password=javohir1401
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

attache.folder=attaches
server.url=http://localhost:${server.port}

telegram.bot.token=8579728669:AAFrgnwOAMAA2O8NxnfnnCrRhuMXRH22dfw
telegram.chat.id=2013021753
app.site-url=https://sarhisob.vercel.app
telegram.bot.username=sarhisob_n1_bot


############################
Email
############################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=komilbayevj@gmail.com
spring.mail.password=phmaheuxiefrmbcb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000
